name: CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Check code health
        uses: ./.github/actions/codehealth
        with:
          run_tests: "false" # Run full testing with coverage below

      - name: Run tests with coverage
        shell: bash
        run: npm test

      - name: Upload coverage info
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true

      - name: Annotate coverage on changed files
        uses: jgillick/test-coverage-annotations@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          coverage: ./coverage/coverage-final.json
          only-changed-files: true
