name: Merge Branches
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "The branch to merge from (default: dev)"
        required: true
        type: choice
        options:
          - dev
          - staging
      target_branch:
        description: "The branch to merge into main (default: staging)"
        required: true
        type: choice
        options:
          - staging
          - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f # v1.4.0
        with:
          type: now
          target_branch: ${{ github.event.inputs.target_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
