# PR guardrail: block pull requests that target main directly.
name: Pull Request Validation

on:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Fail validation
        run: |
          echo "Error: PRs to main are not allowed. Please create one for 'dev'."
          echo "See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request for more information."
          exit 1
